AdvAPP/urls.py
from django.urls import path, include
from . import views

app_name = 'AdvAPP'
# another test commit
urlpatterns = [
    path('homepage/', views.home, name='homepage'),
    path('create/', views.create, name='create'),
    path('play/', views.play, name='play'),
    path('<int:result_text>/', views.playing, name='playing'),
    path('authen/', include('authen.urls'))
]

CS416TextAdv/urls.py
from django.contrib import admin
from django.urls import include, path

# another test commit
urlpatterns = [
    path('AdvAPP/', include('AdvAPP.urls')),
    path('admin/', admin.site.urls),
]

authen/urls.py
from django.urls import path
from . import views


app_name = 'authen'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('stories/', views.user_stories, name='user_stories'),
    path('create/', views.userCreate, name='user_create'),
    path('create/<int:story_id>/<int:text_id>', views.user_add, name='user_add'),
    path('edit/<str:story_title>/', views.user_edit, name='user_edit'),
    path('update/<str:up_type>/<int:id>', views.user_update, name='user_update'),
    path('delete/<str:del_type>/<int:id>', views.user_delete, name='user_delete'),
    path('homepage/', views.homepage, name='auth_homepage'),
    path('play/', views.play, name="auth_play"),
    path('<int:result_text>/', views.playing, name='playing'),
    path('publish/<int:story_id>/', views.publish, name="publish"),
    path('publish/', views.publish, name="pub2")
]

AdvAPP/models.py
from django.db import models
from django.contrib.auth.models import User, AnonymousUser

class Stories(models.Model):
    story_title = models.CharField(max_length=100, default="Choose Your Own Adventure")
    author = models.CharField(max_length=100, default="anonymous")
    published = models.BooleanField(default=False)
    def __str__(self):
        return self.story_title

class AdventureText(models.Model):
    story = models.ForeignKey(Stories, default="", on_delete=models.CASCADE)
    adv_text = models.TextField()
    def __str__(self):
        return self.adv_text

class ChoiceText(models.Model):
    choice_text = models.CharField(max_length=300)
    choice_of = models.ForeignKey(AdventureText, on_delete=models.CASCADE)
    result_text = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

authen/models.py
from django.db import models

# Create your models here.

authen/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User, auth
from django.template import loader

from AdvAPP.models import Stories, AdventureText, ChoiceText

try:
    import tweepy
    from tweepy import RateLimitError
except:
    print("tweepy import error")
from config import *
from . import views


def register(request):
    if request.method == 'POST':
        firstname = request.POST['first_name']
        lastname = request.POST['last_name']
        e_mail = request.POST['email']
        user = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 == password2:
            if User.objects.filter(username = user).exists():
                print("Username is taken, must be unique")
                messages.info(request, 'Username is taken, must be unique')
                return redirect('AdvAPP:authen:register')
            elif User.objects.filter(email = e_mail).exists():
                print("Email is taken, must be unique")
                messages.info(request, 'Email is taken, must be unique')
                return redirect('AdvAPP:authen:register')
            else:
                User.objects.create_user(first_name=firstname, last_name=lastname, email=e_mail, username=user, password=password1)
                print("A user has been created!")
        else:
            print("Passwords do not match!")
            messages.info(request, 'Passwords do not match!')
            return redirect('AdvAPP:authen:register')

        return redirect('AdvAPP:authen:auth_homepage')

    else:
        return render(request, 'authen/register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('AdvAPP:authen:user_stories')
        else:
            messages.info(request, 'Invalid credentials')
            return redirect('AdvAPP:authen:login')
    else:
        return render(request, 'authen/login.html')

def logout(request):
    auth.logout(request)
    return redirect('AdvAPP:homepage')

def user_stories(request):
    if request.user.is_authenticated:
        username = request.user.get_username()
        stories_list = Stories.objects.all().filter(author=username)
        start_list = ChoiceText.objects.all().filter(choice_text="Start", choice_of__story__author=username).values_list('choice_of', flat=True)
        #template = loader.get_template('authen/userstories.html')
        my_dict = dict(zip(start_list, stories_list))

        context = {
            'my_dict': my_dict,
            'stories_list': stories_list,
            'start_list': start_list
        }
        return render(request, 'authen/userstories.html', context)
    else:
        return redirect('AdvAPP:homepage')

def userCreate(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            user = request.user.get_username()
            story_title = request.POST.get("story_title")
            intro_text = request.POST.get("intro_input")
            next_text = request.POST.get("text_input")
            new_story = Stories.objects.create(story_title=story_title, author=user)
            start_text = AdventureText.objects.create(story=new_story, adv_text=intro_text)
            first_text = AdventureText.objects.create(story=new_story, adv_text=next_text)
            ChoiceText.objects.create(choice_text='Start', choice_of=start_text, result_text=first_text.pk)
            return redirect('AdvAPP:authen:playing', start_text.id)
    else:
        return render(request, 'authen/usercreate.html')

def user_edit(request, story_title):
    story = Stories.objects.get(story_title=story_title)

    context = {
        'story' : story,
    }
    return render(request, 'authen/useredit.html', context)

def user_delete(request, del_type, id):
    if del_type == "story":
        story = Stories.objects.get(pk=id)
        story.delete()
    elif del_type == "adventure":
        adv_text = AdventureText.objects.get(pk=id)
        adv_text.delete()
    elif del_type == "choice":
        choice_text = ChoiceText.objects.get(pk=id)
        choice_text.delete()
    return render(request, 'authen/userdelete.html', { 'del_type' : del_type })

def user_update(request, up_type, id):
    if request.method == 'POST':
        if up_type == "story":
            story = Stories.objects.get(pk=id)
            story.story_title = request.POST.get("story_title")
            story.save()
            context = {
                'story': story,
            }
        elif up_type == "adventure":
            adv_text = AdventureText.objects.get(pk=id)
            adv_text.adv_text = request.POST.get("text_input")
            adv_text.save()
            context = {
                'story': adv_text.story,
            }
        elif up_type == "choice":
            choice_text = ChoiceText.objects.get(pk=id)
            choice_text.choice_text = request.POST.get("text_result")
            choice_text.save()
            context = {
                'story': choice_text.choice_of.story,
            }
        return render(request, 'authen/useredit.html', context)
    else:
        if up_type == "story":
            story = Stories.objects.get(pk=id)
            context = {
                'del_type': up_type,
                'story' : story
            }
        elif up_type == "adventure":
            adv_text = AdventureText.objects.get(pk=id)
            context = {
                'del_type': up_type,
                'adv_text' : adv_text
            }
        elif up_type == "choice":
            choice_text = ChoiceText.objects.get(pk=id)
            context = {
                'del_type': up_type,
                'choice_text' : choice_text
            }
        return render(request, 'authen/userupdate.html', context)

def homepage(request):
    try:
        if request.method == 'POST':
            user = request.POST.get('user')
            return render(request, 'homepage.html', {'tweets': getTweetsUser(user)})
        return render(request, 'homepage.html', {'tweets' : getTweets()})
    except:
        print("error with tweepy  API")
    status = "Problem importing tweepy API"
    return render(request, 'homepage.html', {'tweets': status})

def play(request):
    stories_list = Stories.objects.all()
    start_list = ChoiceText.objects.all().filter(choice_text="Start").values_list('choice_of', flat=True)
    template = loader.get_template('play.html')
    my_dict = dict(zip(start_list, stories_list))

    context = {
        'my_dict' : my_dict,
        'stories_list' : stories_list,
        'start_list' : start_list
    }
    return HttpResponse(template.render(context, request))

def playing(request, result_text):
    try:
        adventureText = AdventureText.objects.get(pk=result_text)
    except AdventureText.DoesNotExist:
        raise Http404("Story does not exist")
    return render(request, 'playing.html', {'adventureText': adventureText})

def user_add(request, story_id, text_id):
    if request.method == 'POST':
        story = Stories.objects.get(pk=story_id)
        prev_text = AdventureText.objects.get(pk=text_id)
        if (request.POST.get("select_input") == "null"):
            new_text = request.POST.get("text_input")
            new_choice = request.POST.get("text_result")
            adventure_text = AdventureText.objects.create(story=story, adv_text=new_text)
            ChoiceText.objects.create(choice_text=new_choice, choice_of=prev_text, result_text=adventure_text.id)
            return redirect('AdvAPP:authen:playing', adventure_text.id)
        else:
            new_text = request.POST.get("select_input")
            new_choice = request.POST.get("text_result")
            adventure_text = AdventureText.objects.get(pk=new_text)
            ChoiceText.objects.create(choice_text=new_choice, choice_of=prev_text, result_text=adventure_text.id)
            return redirect('AdvAPP:authen:playing', adventure_text.id)
    else:
        origin_story = Stories.objects.get(pk=story_id)
        title = origin_story.story_title
        return render(request, 'authen/useradd.html',{'story_id':story_id, 'text_id':text_id, 'story' : origin_story, 'title': title})

def publish(request, story_id):
    if request.method == 'POST':
        story = Stories.objects.get(pk=story_id)
        story.published = True
        story.save()
        start_id = str(ChoiceText.objects.get(choice_text="Start", choice_of__story=story_id).choice_of.id)
        tweet_text = story.author + " just published a new story on the site called " + story.story_title + " at JimmyPhas.pythonanywhere.com/AdvAPP/" + start_id
        postTweet(tweet_text)
        return redirect('AdvAPP:authen:auth_play')
    else:
        return render(request, 'authen/publish.html', {'story_id':story_id})

def postTweet(up_status):
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    api = tweepy.API(auth)
    api.update_status(up_status)

def getTweets():
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    api = tweepy.API(auth)
    public_tweets = api.home_timeline(count=10)
    tweets = []
    for tweet in public_tweets:
        status = tweet.text
        tweets.append({'status': status})
    return {'tweets':tweets}

def getTweetsUser(user):
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    api = tweepy.API(auth)
    public_tweets = api.user_timeline(user, count=10)
    tweets = []

templates/authen/login.html
{% extends 'base.html' %}
{% load static %}
{% block nav %} {% include "navbar2.html" %} {% endblock %}
{% block content %}
   <div id="maincontent">
        <form method="post">
            {% csrf_token %}
            <h2>Login</h2>
            Username:<input type="text" name="username" placeholder="Username"><br><br>
            Password:<input type="password" name="password" placeholder="Password"><br><br>
            <input type="submit" value="Login">
            <br><br>
            <button><a href="{% url 'AdvAPP:authen:register' %}">Register</a></button>
        </form>
   </div>
{% endblock %}

templates/authen/publish.html
{% extends 'base.html' %}
{% load static %}
{% block nav %}{% include 'navbar2.html' %}{% endblock %}
{% block content %}
    <h1 id="page">{{ story }}</h1>
    <h3 id="page">Once you publish your story it will be viewable by all users of the website.</h3>
    <h3 id="page">You can still edit your story after it has been published, however you should have a near complete story when you publish.</h3>
    <form action="{% url 'AdvAPP:authen:publish' story_id %}" method="post">
        {% csrf_token %}
        <div id="center">
            <input type="submit" value="Publish">
        </div>
    </form>
{% endblock %}

templates/authen/register.html
{% extends 'base.html' %}
{% load static %}
{% block nav %} {% include "navbar2.html" %} {% endblock %}
{% block content %}
    <div id="maincontent">
        <form method="post">{% csrf_token %}
            First Name:<input type="text" name="first_name" placeholder="Enter first name here" required><br>
            Last Name:<input type="text" name="last_name" placeholder="Enter last name here" required><br>
            E-mail:<input type="text" name="email" placeholder="Enter E-mail here" required><br>
            Username:<input type="text" name="username" placeholder="Enter username here" required><br>
            Password:<input type="password" name="password1" required><br>
            Confirm Password:<input type="password" name="password2" required><br>
            <input type="submit" value="Create User">
        </form>
    </div>
{% endblock %}

templates/authen/useradd.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Create {% endblock %}
{% if user.is_authenticated %}
{% block nav %} {% include "navbar2.html" %} {% endblock %}
{% block content %}
    <h1 id="page">Add to {{ story }}</h1>
    <div id="create">
        <form method="post" name="create_story" id="section">
            {% csrf_token %}
            Enter Choice: <br> <input type="text" name="text_result" placeholder="What choice leads to this part of the story?" id="choice" required>
            <br>
            Enter Story:<br><textarea name="text_input" pattern="\S+" id="write" cols="100" rows="10" placeholder="Write a section of a story here!"></textarea><br>
            <br>
            <select name="select_input" id="select">
                <option value="null">Select an already created section.</option>
                {% for adv in story.adventuretext_set.all %}
                    <option value="{{ adv.pk }}">{{ adv }}</option>
                {% endfor %}
            </select>
            <br>
            <input type="button" value="Save Section" onclick="return checkinputs()">
            <button id="edit" onclick="window.location.href ='../../edit/{{ title }}';">Back to Edit</button>
        </form>
    </div>
    <script>
        function checkinputs() {
            var str = document.getElementById("write").value;
            var newStr = $.trim(str);
            var choice = document.getElementById("choice").value;
            var newChoice = $.trim(choice);
            if (document.getElementById("write").value != "" && document.getElementById('select').value != "null"){
                alert("Please write a section of the story or select a section of the story, not both!");
                return false
            }
            else if (newStr == "" && document.getElementById('select').value == "null") {
                alert("Please write a section of the story or select a section of the story.");
                return false
            }
            else if (newChoice == "") {
                alert("Please enter a choice.");
                return false
            }
            else {
                saveSection();
                return true
            }
        }

        function saveSection(){
            const section = $("#section").serialize();

            $.ajax({
                type: 'POST',
                data: section,
                success: function (data) {
                    console.log(data);
                    alert("Section has been saved!")
                }
            });

            resetBox();
        }

        function resetBox(){
            $("#section")[0].reset();
        }

    </script>
{% endblock %}
{% endif %}

templates/authen/usercreate.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Create {% endblock %}
{% block nav %} {% include "navbar3.html" %} {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <h1 id="page">Create a New Story!</h1>
    <div id="create">
        <form method="post" name="new_story">{% csrf_token %}
            Story Title:<br><input type="text" name="story_title" placeholder="Enter Story title here" id="title" required><br>
            Intro text:<br><textarea name="intro_input" id="intro" cols="100" rows="10" placeholder="Write the introduction for your story here!" required></textarea><br>
            First text:<br><textarea name="text_input" id="first" cols="100" rows="10" placeholder="Write the first section of your story! Players will make decisions from this point." required
            ></textarea><br>
            <br>
            <input type="submit" value="Save Story" onclick="return checknull()">
        </form>
    </div>
    {% else %}
    You are not logged in.
    {% endif %}
    <script>
        function checknull() {
            var title = document.getElementById("title").value
            var intro = document.getElementById("intro").value
            var first = document.getElementById("first").value

            var newtitle = $.trim(title)
            var newintro = $.trim(intro)
            var newfirst = $.trim(first)

            if (newtitle == "" || newintro == "" || newfirst == ""){
                alert("Please fill out all boxes.")
                return false
            }
            else
                return true
        }
    </script>
{% endblock %}

templates/authen/userdelete.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Delete {% endblock %}
{% block nav %} {% include "navbar2.html" %} {% endblock %}

{% block content %}
    {% if user.is_authenticated %}
    <div id="center">
        {% if del_type == "story" %}
            <h2>The Story {{ story }} has been deleted.</h2>
        {% elif del_type == "adventure" %}
            <h2>The adventure text {{ adv_text }} has been deleted.</h2>
        {% elif del_type == "choice" %}
            <h2>The choice text {{ Choice_text }} has been deleted.</h2>
        {% endif %}

        <div>
            <form action="../../play">
                <button type="submit">Return to the Play page</button>
            </form>
        </div>
    </div>
    {% else %}
        <h1>Not logged in! Please Login or Register</h1>
        <button><a href="{% url 'AdvAPP:authen:login' %}">Login</a></button>
    {% endif %}
{% endblock %}

templates/authen/useredit.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Full Outline {% endblock %}
{% block nav %} {% include "navbar2.html" %} {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <h1 id="page">{{ story }}</h1>
    <div id="center">
        <form action="../../delete/{{"story"}}/{{ story.id }}" method="get">
            <button type="submit" id="delete" onclick="return confirmdelete()">Delete Story</button>
        </form>
        <form action="../../update/{{"story"}}/{{ story.id }}" method="get">
            <button type="submit" id="update">Update Story</button>
        </form>
        {% if story.published %}
        {% else %}
            <button><a href="../../publish/{{ story.id }}/">Publish Story</a></button>
        <!--form action="../../publish/{#{ story.id }#}/" method="get">
            <input type="submit" id="publish" value="Publish Story">
        </form-->
        {% endif %}
    </div>
    <br> <br>
    <div id="stories">
    {% if story %}
        <ol>
        {% for adv in story.adventuretext_set.all %}
            <li>{{ adv }}
            <form action="../../delete/{{"adventure"}}/{{ adv.id }}" method="get">
                <button type="submit" id="delete" onclick="return confirmdelete()">Delete Adventure Text</button>
            </form>
            <form action="../../update/{{"adventure"}}/{{ adv.id }}" method="get">
                <button type="submit" id="update">Update Adventure Text</button>
            </form>
                <ul>
                {% for choice in adv.choicetext_set.all %}
                    <li>{{ choice }}</li>
                    <form action="../../delete/{{"choice"}}/{{ choice.id }}" method="get">
                        <button type="submit" id="delete" onclick="return confirmdelete()">Delete Choice Text</button>
                    </form>
                    <form action="../../update/{{"choice"}}/{{ choice.id }}" method="get" >
                        <button type="submit" id="update">Update Choice Text</button>
                    </form>
                {% endfor %}
                </ul>
            </li>
            <a href="/AdvAPP/authen/create/{{ adv.story.pk }}/{{ adv.pk }}">Add new Option</a>
            <br><br>
        {% endfor %}
        </ol>
        {% else %}
            <p>No stories are available.</p>
    {% endif %}
    </div>
    {% else %}
        <h1>Not logged in! Please Login or Register</h1>
        <button><a href="{% url 'AdvAPP:authen:login' %}">Login</a></button>
    {% endif %}

    <script>
        function confirmdelete() {
            var text = "Confirm Delete?"
            if (confirm(text)) {
                return true
            }
            else
                return false
        }
    </script>
{% endblock %}

templates/authen/userstories.html
{% extends 'base.html' %}
{% block nav %} {% include "navbar.html" %} {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <h1>Hello {{ user.username }}</h1>
        <div id="maincontent">
            {% if stories_list %}
            <ul>
            {% for id, value in my_dict.items %}
                <form action="../edit/{{value}}" method="get">
                    <li><a href="/AdvAPP/{{ id }}/">{{ value }} by: {{ value.author }}</a></li>
                    <button type="submit" id="edit">Edit</button>
                </form>
                <br>
            {% endfor %}
            </ul>
            <button><a href="{% url 'AdvAPP:authen:user_create' %}">Create New Story</a></button>
            {% else %}
                <p>No stories are available. Create a story!</p>
                <button><a href="{% url 'AdvAPP:authen:user_create' %}">New Story</a></button>
            {% endif %}
            {% else %}
                <h1>Not logged in! Please Login or Register</h1>
                <button><a href="{% url 'AdvAPP:authen:login' %}">Login</a></button>
            {% endif %}
        </div>
{% endblock %}

templates/authen/userupdate.html
{% extends 'base.html' %}
{% block title %} Update {% endblock %}
{% block nav %} {% include "navbar2.html" %} {% endblock %}

{% block content %}
    <div id="create">
    {% if user.is_authenticated %}
        {% if del_type == "story" %}
            <form method="post">
                {% csrf_token %}
                Story Title:<br><input type="text" id="title" name="story_title" placeholder="Change Story title here" value="{{ story }}" required><br>
                <br>
                <button type="submit" onclick="return checknull1()">Save</button>
            </form>
        {% elif del_type == "adventure" %}
            <form method="post">
                {% csrf_token %}
                Enter Story:<br><textarea name="text_input" id="adv" cols="100" rows="10" placeholder="Change the section of a story here!" required>{{ adv_text }}</textarea><br>
                <br>
                <button type="submit" onclick="return checknull2()">Save</button>
            </form>
        {% elif del_type == "choice" %}
            <form method="post">
                {% csrf_token %}
                Enter Choice: <br> <input type="text" id="choice" name="text_result" placeholder="What choice leads to this part of the story?" value="{{ choice_text }}" required>
                <br>
                <button type="submit" onclick="return checknull3()">Save</button>
            </form>
        {% endif %}
    {% else %}
        <h1>Not logged in! Please Login or Register</h1>
        <br>
        <button><a href="{% url 'AdvAPP:authen:login' %}">Login</a></button>
    {% endif %}
    </div>

    <script>
        function checknull1() {
            var title = document.getElementById("title").value
            var newtitle = $.trim(title)
            if (newtitle == "") {
                alert("Please input a title.")
                return false
            }
            else
                return true
        }
        function checknull2() {
            var adventure = document.getElementById("adv").value
            var newadventure = $.trim(adventure)
            if (newadventure == "") {
                alert("Please input a text.")
                return false
            }
            else
                return true
        }
        function checknull3() {
            var choice = document.getElementById("choice").value
            var newchoice = $.trim(choice)
            if (newchoice == "") {
                alert("Please input a choice.")
                return false
            }
            else
                return true
        }
    </script>
{% endblock %}